### ISSUE TITLE
v0.48.0 can't be used as a conda dependency

### ISSUE THREAD

**Issue by aldanor** [conda-forge/websocket-client-feedstock#10]
@pmlandwehr, @scopatz -- wonder if you'd have any ideas about it: apparently v0.48.0 can't be used as a conda dependency anymore when building a Python package with conda-build, due to Python 3 version of `websocket-client` somewhy reporting to distutils it depends on `backports.ssl_match_hostname` (see https://github.com/websocket-client/websocket-client/issues/439 for details). 

I couldn't find any relevant code changes between v0.47.0 and v0.48.0, so was wondering whether it's some bizarre conda recipe issue.

**Comment by scopatz** [comment]
I think this means we need to add backports as a dependency, then.

**Comment by scopatz** [comment]
Thanks for reporting!

**Comment by scopatz** [comment]
actually it relies on `backports.ssl_match_hostname`

**Comment by nehaljwani** [comment]
Relevant code here: https://github.com/websocket-client/websocket-client/blob/v0.48.0/setup.py#L17-L21

**Comment by aldanor** [comment]
Hmm... the real problem is that `websocket-client` should never ever report that it needs this backports package for Python 3? Note: I was running Python 3.6.

I think it's these lines that actually mess it up (e.g. if you run `python setup.py test install`): https://github.com/websocket-client/websocket-client/blob/v0.48.0/setup.py#L23

**Comment by orodbhen** [comment]
It looks like the conda package is actually being built for Python 2.7, which causes it to depend on `backports.ssl_match_hostname`. 

I don't understand that well how the CI setup works, but it seems to be controlled by `.ci_support/linux_.yaml`, which Specifies Python 2.7. The name of the generated package just has `py_0` in it, instead of `py27_0` or `py36_0`. I supposed that's why Python 3.6 packages are still able to use it as a dependency.

In my case it's pulled in by the `docker` package, but only as a `run` requirement, so it doesn't fail until run-time, with `DistributionNotFound` from `pkg_resources`. This is triggered by `backports.ssl_match_hostname` being listed in the installed package's `requirements.txt` file.

**Comment by aldanor** [comment]
`py_0` means it's a ["noarch" conda package](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages) that doesn't contain compiled bytecode which gets compiled at the linking stage.

However websocket-client seems to be using fancy distutils constructs that don't play well with all this. If they don't fix it, maybe this recipe could be converted to a separate py27/py35/py36 instead of noarch?

**Comment by scopatz** [comment]
Thanks for pointing this out @aldanor - new arch based PR in #11

**Comment by pmlandwehr** [comment]
merged, so closing this.
